name = "backend-worker"
main = "worker.js"           # <-- your Worker script file
compatibility_date = "2025-10-04"
type = "javascript"          # or "webpack" / "modules" if using modules

# Optional: KV namespace binding
kv_namespaces = [
  { binding = "PublicContent", id = "3512f00ee6994736a2eae736ad6c191a" }
]
